### ISSUE TITLE
ckb-indexer with docker

### ISSUE THREAD

**Issue by HFFP** [nervosnetwork/ckb-indexer#34]
i find ckb-indexer in docker hub,  [https://hub.docker.com/r/nervos/ckb-indexer](url)

but when i request node rpc i got result, but when i use indexer rpc i got 502 error.

so, have some special params i did't set? or some else?

i just run this command

`docker run -d -it  -p 8117:9115  --name=ckb-testnet-indexer  -e "CKB_NETWORK=testnet" -v "$PWD/data":/data nervos/ckb-indexer:v0.37.0
`

**Comment by quake** [comment]
Which RPC are you calling? btw, this docker is packed with old version ckb-indexer, we will upload a new version later.

**Comment by HFFP** [comment]
I saw the update, so I also need to run a ckb node?

**Comment by quake** [comment]
yes, ckb-indexer will connect to ckb node's default rpc uri at `http://127.0.0.1:8114`

**Comment by HFFP** [comment]
> yes, ckb-indexer will connect to ckb node's default rpc uri at `http://127.0.0.1:8114`

ok. thank you!

**Comment by HFFP** [comment]
not found image

**Comment by HFFP** [comment]
`version: "3"

services:
  ckb:
    image: nervos/ckb
    container_name: ckb-testnet-node
    command: run
    environment:
      - CKB_CHAIN=testnet
    volumes:
      - ckb-testnet:/var/lib/ckb
    ports:
    - 8114:8114

  ckb-indexer:
    image: tockb/ckb-indexer
    container_name: ckb-testnet-indexer
    ports:
    - 8116:8116
    volumes:
      - ckb-testnet-indexer:/data
    command: ckb-indexer -s /data -c http://ckb:8114 -l 0.0.0.0:8116
    depends_on:
      - ckb

volumes:
  ckb-testnet:
  ckb-testnet-indexer:
`

if anyone has the same problem, I use docker-compose as above to solve

**Comment by HFFP** [comment]
```
version: "3"

services:
  ckb:
      image: nervos/ckb
      container_name: ckb-testnet-node
      command: run
      environment:
        - CKB_CHAIN=testnet
      volumes:
        - ckb-testnet:/var/lib/ckb
      ports:
      - 8114:8114

  ckb-indexer:
      image: tockb/ckb-indexer
      container_name: ckb-testnet-indexer
      ports:
      - 8116:8116
      volumes:
        - ckb-testnet-indexer:/data
      command: ckb-indexer -s /data -c http://ckb:8114 -l 0.0.0.0:8116
      depends_on:
        - ckb

volumes:
ckb-testnet:
ckb-testnet-indexer:
```

if anyone has the same problem, I use docker-compose as above to solve
